# Generated by Django 5.1.4 on 2025-01-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_theater_url_alter_subscription_theater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name']},
        ),
    ]
